// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZfaqKo9ilF45yo8PQtMSaSoGhBUoseoM',
    appId: '1:470989831835:web:eddfb07cead4664bd5d03e',
    messagingSenderId: '470989831835',
    projectId: 'flutter-chat-ms-2025',
    authDomain: 'flutter-chat-ms-2025.firebaseapp.com',
    storageBucket: 'flutter-chat-ms-2025.firebasestorage.app',
    measurementId: 'G-J62JRFV7RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzM6UJ0ZWfQgkdzAUM8GEJyufKO4Z0Svc',
    appId: '1:470989831835:android:9c30b929954c89ebd5d03e',
    messagingSenderId: '470989831835',
    projectId: 'flutter-chat-ms-2025',
    storageBucket: 'flutter-chat-ms-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbzb4iF-KvYQW_ViUze9FkXeSk4HdvcTI',
    appId: '1:470989831835:ios:b543d54691de629cd5d03e',
    messagingSenderId: '470989831835',
    projectId: 'flutter-chat-ms-2025',
    storageBucket: 'flutter-chat-ms-2025.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbzb4iF-KvYQW_ViUze9FkXeSk4HdvcTI',
    appId: '1:470989831835:ios:b543d54691de629cd5d03e',
    messagingSenderId: '470989831835',
    projectId: 'flutter-chat-ms-2025',
    storageBucket: 'flutter-chat-ms-2025.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZfaqKo9ilF45yo8PQtMSaSoGhBUoseoM',
    appId: '1:470989831835:web:9c1aaa88a80ffbf2d5d03e',
    messagingSenderId: '470989831835',
    projectId: 'flutter-chat-ms-2025',
    authDomain: 'flutter-chat-ms-2025.firebaseapp.com',
    storageBucket: 'flutter-chat-ms-2025.firebasestorage.app',
    measurementId: 'G-Z75QSFHRDM',
  );
}
